name: Generate Doxygen Documentation

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  doxygen:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Doxygen
        run: sudo apt-get install -y doxygen

      - name: Generate documentation
        run: |
          cd laboratories/cicd-documentation
          doxygen Doxyfile

      - name: Upload documentation artifact
        uses: actions/upload-artifact@v4
        with:
          name: doxygen-docs
          path: laboratories/cicd-documentation/html/
